---
title: "Project Charter"
author: "Enqun Wang (EW), Yiyan Zhou (YZ)"
date: "April 21, 2016"
output: html_document
---

#### Problem Statement:

Trading volume reflects the status of operation of the P2P company objectively. This problem happens on each workday in a three-month period started from January 4, 2016. Considering the issue of confidential policy, we can only collect the data of 3 months. As a result, it is reasonable to assume that we are at the end of the date that the data is collected to do the project. Our project is based on observational data, so we can hardly get a cause-and-effect conclusion. Beside, as the data only covers three months, we cannot find solution considering seasonal variation. 

> It would be good to capture the trading volume as it is today – how many shares? how many companies? What is the rate of increase?  What is the desired rate?, …  Can you tell me what a defect is?

#### Project Objective:

Increase the trading volume of the platform <u>(by how much in what time frame? – this would be a company objective…)</u> from the the date the project started, and achieve a goal that the company is in a healthy improving state. Our project has no specific date of completion; in another word, the project is through the whole life of the company.

#### Project Team

| Name | Role | Comments | Phone |
|---|---|---|---|
|Enqun Wang |Operation Analyst |Organize the project and assign the detailed work to team members | 7202315851 |
|Yiyan Zhou |Operation Analyst |Finish what the leader assigned and give advises |9702945303 |
|Chee-Yong Tan |Operation executive officer |Adjust the strategies | |

#### Project Definition and Scoping

**Metrics (unit of measure)**

| variables  | variables  |
|---|---|
|Trading volume   |Recode the total trading volume in the platform in 24 hours. Unit: Chinese Yuan.   |
|Products weighted rate of return   |Recode the weighted rate of return for the products of the day. Weight: Transaction amount; Unit: %. |
|Product weighted term   |Recode the product weighted term of the day. Weight: Transaction amount; Unit: month.   |
|Amount of receiving the lucky money   |Recode the amount of users’ receiving lucky money of the day. Unit: Chinese Yuan.|
|Amount of using the lucky money   |Recode the total amount of users’ using the lucky money of the day. Unit: Chinese Yuan.|
|Total account balance   |Record all users’ total account balance at 12:00 am. Unit: Chinese Yuan|
|Net capital inflows|Recode the platform’s (Capital inflows - Capital outflows). Unit: Chinese Yuan.|
|The closing price of treasury bonds repurchase in 7 days.|The closing price of treasury bonds repurchase in 7 days. Price: APR; Unit: %.|
|One day term weighted interbank rates|The weighted interbank rates in inter-bank market. Unit: %.|
|Overnight SHIBOR|Short-term interest rates among banks lending to each other applicable. Unit: %.|
|Closing price of Shanghai Stock Exchange.|Everyday’s closing price of Shanghai Stock Exchange|
|Growth enterprise market(GEM) index|The weighted average of the total shares in the GEM, regarding the starting date as Datum point.|

**Critical to Satisfaction (linkage to customer):**

The customer, operation executive officer (OEO), is interested in this problem because he makes further decision based on this process.
And what does he want to see?

**Defect Definition (include opportunity):**

Assuming that the whole environment of the finance market in China is mild, a significant decrease or no material increase may be regarded as a defect in the project.  Give me an operational definition of significant, material

**Scope of Project:**

The project started in March 4, 2015, and the data is collected for 3 months. Assuming that we are at the end of the data collected to do the project. 




